language: python

python:
- "3.5"

dist: trusty
sudo: true

addons:
 apt:
  sources: [deadsnakes]
  packages: [python3.5-dev]

before_install:
- sudo apt-get remove python3.4 python3.4-dev
- sudo apt-get purge python3.4 python3.4-dev
- sudo apt-get autoremove
- sudo apt-get install -y cmake git g++ wget
- sudo apt-get install python3.5 python3.5-dev
- wget https://downloads.sourceforge.net/project/tclap/tclap-1.2.1.tar.gz
- wget https://root.cern.ch/download/root_v6.08.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
- tar -xf tclap-1.2.1.tar.gz
- cd tclap-1.2.1
- ./configure
- make
- sudo make install
- cd ..
- tar -xf root_v6.08.06.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
- . root/bin/thisroot.sh
- cd ..
- git clone https://github.com/AAAlvesJr/Hydra.git
- git clone https://github.com/pybind/pybind11.git


script:
- cmake -DHYDRA_INSTALL_PATH=../Hydra -DPYBIND11_INSTALL_PATH=../pybind11/include -DTHRUST_INSTALL_PATH=../Hydra temp
- make all
- ls
- ls temp/
- python -m unittest discover -s temp/tests -p 'test_*.py'